// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZmbRnGfQatg3ohbJiCLUmiEUVmiLlFb8',
    appId: '1:733483686093:web:43d9f9cc59538bfdabf184',
    messagingSenderId: '733483686093',
    projectId: 'local-first-app-7f65c',
    authDomain: 'local-first-app-7f65c.firebaseapp.com',
    storageBucket: 'local-first-app-7f65c.firebasestorage.app',
    measurementId: 'G-PTWYQZ1S2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDshOzlY2MLd0msI0bbBs8kKNYBJ8LTs',
    appId: '1:733483686093:android:f16b0b77e7c0cae0abf184',
    messagingSenderId: '733483686093',
    projectId: 'local-first-app-7f65c',
    storageBucket: 'local-first-app-7f65c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaCRtt2mFY5K9iDXuBUFM2tdqJfJt1wkQ',
    appId: '1:733483686093:ios:5a4def041bf0106fabf184',
    messagingSenderId: '733483686093',
    projectId: 'local-first-app-7f65c',
    storageBucket: 'local-first-app-7f65c.firebasestorage.app',
    iosBundleId: 'io.github.moyeenhaider3.localfirst',
  );
}
